version: "3"
services:
  serve:
    container_name: export-service
    # image: brewery/export-service:dev-latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${PORT}
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
